### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'no_args_is_help'

### ISSUE THREAD

**Issue by superbsky** [suqingdong/pypubmed#2]
I am getting this error after the installation:

TypeError: __init__() got an unexpected keyword argument 'no_args_is_help'

Steps to reproduce:
python -V
Python 3.6.9

pip3 -V
pip 21.1.2 from /home/***/.local/lib/python3.6/site-packages/pip (python 3.6)

pip3 install pypubmed
...
Successfully installed et-xmlfile-1.1.0 googletrans-4.0.0rc1 impact-factor-1.0.8 openpyxl-3.0.7 prettytable-2.1.0 pypubmed-1.0.15 simple-googletrans-1.0.2 simple-loggers-1.0.4 w3lib-1.22.0 webrequests-1.0.4

pypubmed
Traceback (most recent call last):
  File "/home/genx/.local/bin/pypubmed", line 5, in <module>
    from pypubmed.bin.cli import main
  File "/home/genx/.local/lib/python3.6/site-packages/pypubmed/bin/cli.py", line 7, in <module>
    from ._search import search, advance_search
  File "/home/genx/.local/lib/python3.6/site-packages/pypubmed/bin/_search.py", line 37, in <module>
    @click.pass_obj
  File "/home/genx/.local/lib/python3.6/site-packages/click/decorators.py", line 115, in decorator
    cmd = _make_command(f, name, attrs, cls)
  File "/home/genx/.local/lib/python3.6/site-packages/click/decorators.py", line 89, in _make_command
    callback=f, params=params, **attrs)
TypeError: __init__() got an unexpected keyword argument 'no_args_is_help'

**Comment by suqingdong** [comment]
update your click package: `pip3 install -U click`

**Comment by superbsky** [comment]
thank you! it works now!

**Comment by roywhite98** [comment]
I am getting this error when I try this :

~\home> pypubmed

ImportError: cannot import name 'ImpactFactor' from 'impact_factor' (E:\Python\Lib\site-packages\impact_factor\__init__.py)

python version 3.11.2
